# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# http://go.microsoft.com/fwlink/?LinkId=248926

# Builds the library for Windows Desktop and UWP.

schedules:
  - cron: "0 3 * * *"
    displayName: 'Nightly build'
    branches:
      include:
        - main

# GitHub Actions handles MSBuild for CI/PR
trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - '.azuredevops/pipelines/DirectXTex-GitHub-Dev17.yml'
      - DirectXTex/Shaders/CompileShaders.cmd

resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

variables:
  Codeql.Enabled: false

pool:
  vmImage: windows-2022

jobs:
  - job: DESKTOP_BUILD
    displayName: 'Windows Desktop'
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    strategy:
      maxParallel: 3
      matrix:
        Release_arm64:
          BuildPlatform: ARM64
          BuildConfiguration: Release
          SpectreMitigation: false
        Debug_arm64:
          BuildPlatform: ARM64
          BuildConfiguration: Debug
          SpectreMitigation: false
        Release_x64:
          BuildPlatform: x64
          BuildConfiguration: Release
          SpectreMitigation: false
        Debug_x64:
          BuildPlatform: x64
          BuildConfiguration: Debug
          SpectreMitigation: false
        Release_x86:
          BuildPlatform: x86
          BuildConfiguration: Release
          SpectreMitigation: false
        Debug_x86:
          BuildPlatform: x86
          BuildConfiguration: Debug
          SpectreMitigation: false
        Release_arm64_SpectreMitigated:
          BuildPlatform: ARM64
          BuildConfiguration: Release
          SpectreMitigation: 'Spectre'
        Debug_arm64_SpectreMitigated:
          BuildPlatform: ARM64
          BuildConfiguration: Debug
          SpectreMitigation: 'Spectre'
        Release_x64_SpectreMitigated:
          BuildPlatform: x64
          BuildConfiguration: Release
          SpectreMitigation: 'Spectre'
        Debug_x64_SpectreMitigated:
          BuildPlatform: x64
          BuildConfiguration: Debug
          SpectreMitigation: 'Spectre'
        Release_x86_SpectreMitigated:
          BuildPlatform: x86
          BuildConfiguration: Release
          SpectreMitigation: 'Spectre'
        Debug_x86_SpectreMitigated:
          BuildPlatform: x86
          BuildConfiguration: Debug
          SpectreMitigation: 'Spectre'
    steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: VSBuild@1
        displayName: Build solution DirectXTex_Desktop_2022.sln
        inputs:
          solution: DirectXTex_Desktop_2022.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=$(SpectreMitigation)
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArchitecture: x64
        condition: ne(variables['BuildPlatform'], 'ARM64')
      - task: VSBuild@1
        displayName: Build solution DirectXTex_Desktop_2022_Win10.sln
        inputs:
          solution: DirectXTex_Desktop_2022_Win10.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64 /p:SpectreMitigation=$(SpectreMitigation)
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArchitecture: x64

  - job: UWP_BUILD
    displayName: 'Universal Windows Platform (UWP)'
    timeoutInMinutes: 120
    cancelTimeoutInMinutes: 1
    strategy:
      maxParallel: 3
      matrix:
        Release_arm64:
          BuildPlatform: ARM64
          BuildConfiguration: Release
        Debug_arm64:
          BuildPlatform: ARM64
          BuildConfiguration: Debug
        Release_x64:
          BuildPlatform: x64
          BuildConfiguration: Release
        Debug_x64:
          BuildPlatform: x64
          BuildConfiguration: Debug
        Release_x86:
          BuildPlatform: x86
          BuildConfiguration: Release
        Debug_x86:
          BuildPlatform: x86
          BuildConfiguration: Debug
    steps:
      - checkout: self
        clean: true
        fetchTags: false
      - task: VSBuild@1
        displayName: Build solution DirectXTex_Windows10_2022.sln
        inputs:
          solution: DirectXTex_Windows10_2022.sln
          msbuildArgs: /p:PreferredToolArchitecture=x64
          platform: '$(BuildPlatform)'
          configuration: '$(BuildConfiguration)'
          msbuildArchitecture: x64
